version: 2.0
jobs:
  test:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
        name: 'Install dependencies'
        command: |
          npm install
      - save_cache
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - run:
        name: 'Run tests'
        command: |
          npm run validate